name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@master
      with:
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: nos1000jours/${{ env.project }}
        dockerbuildargs: |
          NEXT_PUBLIC_API_URL=https://backoffice-preprod-les1000jours.dev.fabrique.social.gouv.fr

  ##############################################################################
  ## GENERATE PRODUCTION MANIFESTS
  ##############################################################################
  manifests:
    name: Production manifests
    runs-on: ubuntu-latest
    steps:

    - name: Use autodevops manifests generation
      uses: SocialGouv/actions/autodevops-manifests@master
      with:
        environment: "prod"

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register, manifests]
    environment:
      name: production
      url: https://${{ env.namespace }}.${{ env.SOCIALGOUV_BASE_DOMAIN }}
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-deploy@master
      with:
        environment: "prod"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
